name: root
channels:
  - pytorch
  - defaults
dependencies:
  - cpuonly=1.0=0
  - pip=22.3.1
  - python=3.8
  - pytorch=1.13.0=py3.8_cpu_0
  - pip:
    - cloudpickle
    - opencv-python-headless
    - pandas
    - numpy
    - matplotlib
    - stable-baselines3>=2.0.0
    - sphinx>=5,<8
    - sphinx_rtd_theme>=1.3.0
    - sphinx_copybutton
